services:
  sample-boilerplate:  
    # image: localregistry/sample-boilerplate:latest
    build:
      context: .
      dockerfile : ./Dockerfile
    container_name: sample-boilerplate
    volumes:
      - ./workspace:/opt/workspace
      - ./cache:/root/.cache/
    working_dir: /opt/workspace
    entrypoint: uvicorn api:app --host 0.0.0.0 --port 7890 --reload

    ports:
      - 7890:7890

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
